apiVersion: v1
kind: Service
metadata:
  name: meet-doctor-endpoint
  labels:
    app: meet-doctor
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 31300
    nodePort: 31300
  selector:
    app: meet-doctor
    tier: backend
