package meet.doctor.dto;

public enum Specialization {

    ALLERGIST,
    IMMUNOLOGIST,
    ANESTHESIOLOGIST,
    CARDIOLOGIST,
    DERMATOLOGIST,
    GASTROENTEROLOGIST,
    HEMATOLOGIST,
    ONCOLOGIST,
    INTERNAL_MEDICINE_PHYSICIAN,
    NEPHROLOGIST,
    NEUROLOGIST,
    NEUROSURGEON,
    OBSTETRICIAN,
    GYNECOLOGIST,
    NURSE_MIDWIFERY,
    OCCUPATIONAL_MEDICINE_PHYSICIAN,
    OPHTHALMOLOGIST,
    SURGEON,
    ORTHOPAEDIC_SURGEON,
    OTOLARYNGOLOGIST,
    PATHOLOGIST,
    PEDIATRICIAN,
    PLASTIC_SURGEON,
    PODIATRIST,
    PSYCHIATRIST,
    PULMONARY_MEDICINE_PHYSICIAN,
    RADIATION_ONCONLOGIST,
    DIAGNOSTIC_RADIOLOGIST,
    RHEUMATOLOGIST,
    UROLOGIST;

}
